### ISSUE TITLE
the communication between the user and the node seems to be not needed to send the contract id

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_pallets#5]
![image](https://user-images.githubusercontent.com/64129/124763315-1ba4a300-df34-11eb-8772-170f7e30db33.png)

the data should be IMO communicated to the node without the intervention of the user

**Comment by DylanVerstraete** [comment]
I agree that it's a tedious step for the user. Since we cannot create a contract on chain over the RMB (because we need a backend that can receive this request and create the object on chain) we can actually skip the step where the user needs to push the contract ID to the node.

The user creates the contract with a workload definition on chain, the node stream the events from the chain and listens to `contract_created` events. Whenever a node sees this event, it decodes the event and reads the `contract_id`. It can then fetch this contract by ID from the chain and read its contents and start billing.

**Comment by muhamadazmy** [comment]
I understand your point but note the following:
- The data on the contract can have sensitive information, so only the user can/should can read it. hence allowing the node also to be read this from the chain goes against this requirement.
- The node can still miss the blockchain events (network issue, node was down, or any other reason) so it's better if the user can ask the node to deploy something instead then the node will still validate the existence (and hash) of the contract.
- The user will still need to contact the node anyway to actually query the status of his deployment. 
- The contract is mainly for billing, it's an agreement between the node that he is going to deploy a certain set of workloads it's not a carrier of information
